### ISSUE TITLE
Releasing releases with a release notes

### ISSUE THREAD

**Issue by ohault** [microsoft/demikernel#1284]
Can you please continue to publish on Github up-to-date Releases with Release notes or at least Tags with a release notes as previously ?

Thanks

**Comment by ppenna** [comment]
Hello, releases are produced for major version bumps.

**Comment by ohault** [comment]
Where is release notes of 1.5 ?

**Comment by ohault** [comment]
As for https://github.com/microsoft/demikernel/releases/tag/v1.4 and previous versions, can you please continue to write a What's Changed section for your users ?

https://github.com/microsoft/demikernel/releases/tag/v1.5 is so empty.

**Comment by ppenna** [comment]
@ohault these logs are generated automatically and for some reason they were not generated when I created the tag for v1.5. I am sorry for this.

**Comment by ohault** [comment]
> @ohault these logs are generated automatically and for some reason they were not generated when I created the tag for v1.5. I am sorry for this.

You're welcome @ppenna . Thank you. I was just my two cents of the day.
