### ISSUE TITLE
[CI] CI is not logging correct log files

### ISSUE THREAD

**Issue by iyzhang** [microsoft/demikernel#1326]
## Description

For Catmem ping-pong, the client log files seem to be stored for both the server and the client.

## How to Reproduce

1. Run CI
2. Look at log files for server and client. They are identical.

[system-test-pipe-ping-pong-client-52.229.35.37.stderr.txt](https://github.com/user-attachments/files/16075541/system-test-pipe-ping-pong-client-52.229.35.37.stderr.txt)
[system-test-pipe-ping-pong-server-52.229.35.37.stderr.txt](https://github.com/user-attachments/files/16075542/system-test-pipe-ping-pong-server-52.229.35.37.stderr.txt)

**Comment by anandbonde** [comment]
Catmem codebase was deleted, hence closing this issue.
