### ISSUE TITLE
[inetstack] Rename "Options" that are Actually Configuration Parameters as Such

### ISSUE THREAD

**Issue by BrianZill** [microsoft/demikernel#185]
This is about code clarity.

Currently, the stack has several structures referred to as "options" that are really configuration parameters.  This can be confusing, as some protocols (particularly TCP) have actual optional behaviors and/or packet header fields that are named "options".  And while there are configuration parameters that control optional behaviors, they're still configuration parameters.

We should name our structures carefully to avoid confusion.

**Comment by iyzhang** [comment]
This has been renamed.
