### ISSUE TITLE
[inetstack] Support Fast Lookup for Bound Addresses and Ports

### ISSUE THREAD

**Issue by ppenna** [microsoft/demikernel#190]
Context
---------

We currently miss a fast lookup mechanism to determine whether or not a given address/port pair is bound.

Proposed Solution
---------------------

We should introduce some structure that would enable us to quickly determine if a given address/port pair is bound.

Alternative Solutions
------------------------

We can consider refactoring existing structures to provide this semantic.

**Comment by iyzhang** [comment]
This is provided by function `is_addr_in_use` in runtime/mod.rs
