### ISSUE TITLE
[inetstack] Extraneous Hash Table Lookups from QDesc to Connection State

### ISSUE THREAD

**Issue by BrianZill** [microsoft/demikernel#191]
Currently, getting from a Queue Descriptor to an Established connection takes two separate hash table lookups.  These lookups occur for several different fast-path API calls, and presumably could be reduced to a single hash table lookup, or something even faster.

**Comment by iyzhang** [comment]
This is no longer the case now that we have unified on NetworkTransport's SocketDescriptor

**Comment by ppenna** [comment]
@iyzhang, as far as I recall, in most places as Brian suggested, we could invert the casting logic. Could you point us to at least three points in the code where such casting is not possible?
