### ISSUE TITLE
[inetstack] Check API for User Errors at Lower Level

### ISSUE THREAD

**Issue by BrianZill** [microsoft/demikernel#200]
We don't have a consistent place to check API calls for user errors.  For example, in the send path, there is a check that the user isn't attempting to send an absurd amount of data in a single send.  This check isn't performed until we're all the way up in Sender::send().  This presumably could/should be done at a lower level, perhaps even in the protocol-independent part of the API code.

**Comment by iyzhang** [comment]
This is checked by ensuring that we don't allocate buffers that are too large, but I left the check in the inetstack as well just in case we allocate buffers some other way in the future.
