### ISSUE TITLE
[inetstack] Connection State is Never Cleaned Up

### ISSUE THREAD

**Issue by gatoWololo** [microsoft/demikernel#212]
The `Inner` struct for `TcpPeer` holds the established connections on the `established: HashMap<(Ipv4Endpoint, Ipv4Endpoint), EstablishedSocket<RT>>` field. It seems the `remove` method is never called on this HashMap. So while the socket state is updated, the established socket is never cleaned up.

At some point this state should probably be cleared from `established`.

**Comment by iyzhang** [comment]
This was closed by PR #1304
