### ISSUE TITLE
[pdpix] Add Support for Windows

### ISSUE THREAD

**Issue by anandbonde** [microsoft/demikernel#274]
Context
======

Bing is a important collaborator for Demikernel and a path to production. Many Bing services run on Windows. So, having a fully supported Windows port is crucial.

Goal:

- Provide a seamless build mechanism for Linux and Windows (based on Makefiles)
- Build all Demikernel components (including tests and examples) on Windows
- Successfully run all tests Demikernel tests on Windows
- Port all LibOSes to Windows

Proposed Solution
=============

- [x] Support a seamless build mechanism for Linux and Windows
    - [x] Split Makefiles for Linux and Windows (https://github.com/demikernel/demikernel/pull/273)
    - [x] Add Windows Makefiles and ensure that all components build successfully (https://github.com/demikernel/demikernel/pull/309)
- [x] Create a hierarchy of subsystems in the Platform Abstraction Layer (https://github.com/demikernel/demikernel/pull/305)
- [x] Implement a "Catnap"-like solution for Windows (https://github.com/demikernel/demikernel/pull/314)
- [x] Add DPDK support on Windows
- [x] Use PAL in all LibOSes
    - [x] Use PAL in Catnip
- [x] Support Bing team to build and test on Windows

**Comment by BrianZill** [comment]
The hierarchy of subsystems in the Platform Abstraction Layer should be based on subsystem alone.  In other words, there should be a separate file for each subsystem, with organizing directories only for groupings of subsystems.

For example, for the sockets API, everything related to it should go into the same sockets.rs file.  This file should either be directly in the top level (under pal), or in a Networking directory (if we end up with too many files directly under pal).  There should be no "platform" directories.  The sockets.rs file should contain definitions for everything that is platform specific (constants, function names, structures, whatever).  Inside the file, the definitions should be organized by thing, and not by platform.

I.e.,
```
#[cfg(target_os = "windows")]
use windows::Win32::Networking::WinSock;

// Socket Address Types
#[cfg(target_os = "linux")]
pub const AF_INET: i32 = libc::AF_INET;
#[cfg(target_os = "windows")]
pub const AF_INET: i32 = WinSock::AF_INET.0 as i32;

// Socket Types
#[cfg(target_os = "linux")]
pub const SOCK_DGRAM: i32 = libc::SOCK_DGRAM;
#[cfg(target_os = "windows")]
pub const SOCK_DGRAM: i32 = WinSock::SOCK_DGRAM as i32;
#[cfg(target_os = "linux")]
pub const SOCK_STREAM: i32 = libc::SOCK_STREAM;
#[cfg(target_os = "windows")]
pub const SOCK_STREAM: i32 = WinSock::SOCK_STREAM as i32;
```
For this example I alphabetized each thing's platform-specific version by target_os (i.e., the "linux" one before the "windows" one) and to a limited extent the things themselves (i.e., SOCK_DGRAM before SOCK_STREAM).  But the things themselves should obviously be grouped by functionality/applicability (like all socket types together).

Also, if the libc crate is linux specific (as it appears to be from this), then all "use" of it should be platform-specific, as well.

**Comment by iyzhang** [comment]
Closing this since Bing clearly has deployed :)
