### ISSUE TITLE
[test] SharedRingBuffer Concurrent Unit Test Has a Race Condition and Tests Too Little

### ISSUE THREAD

**Issue by BrianZill** [microsoft/demikernel#319]
Description
========

The `SharedRingBuffer` test "[shm-test-ring-buffer-concurrent](https://github.com/demikernel/demikernel/blob/0ded82656e81cd2eaf3dc874f452569758a4291a/src/rust/collections/shared_ring.rs#L113)" has a race condition that can cause inadvertent test failure.  It creates a writer and a reader thread, with [the writer creating a shared memory resource](https://github.com/demikernel/demikernel/blob/0ded82656e81cd2eaf3dc874f452569758a4291a/src/rust/collections/shared_ring.rs#L118) that [the reader then opens](https://github.com/demikernel/demikernel/blob/0ded82656e81cd2eaf3dc874f452569758a4291a/src/rust/collections/shared_ring.rs#L133).  [If the resource isn't present when the reader attempts to open it, the test fails](https://github.com/demikernel/demikernel/blob/0ded82656e81cd2eaf3dc874f452569758a4291a/src/rust/collections/shared_ring.rs#L135).  In an attempt to make the writer win this race, [the reader waits 100ms upon startup](https://github.com/demikernel/demikernel/blob/0ded82656e81cd2eaf3dc874f452569758a4291a/src/rust/collections/shared_ring.rs#L131) before trying to open the resource.  But there is no guarantee that the writer will be able to create the resource in that time.

I'm also surprised that the test doesn't appear to be testing ring wrap-around (the test appears to just fill the ring once and empty it once) or guaranteeing actual interleaved accesses to the ring buffer (right now the writer thread could be scheduled and run until it is waiting on ring empty, the reader thread could be scheduled and run until it has read everything and exit, and then the writer could be scheduled and notice the ring is empty and exit.  That's not much interleaving being tested, and if the writer's checks for the ring being empty were failing (writer exited early) nothing would notice.

How to Reproduce
=============

Read the code (I've added permalinks to the various sections of the code mentioned in the Description above).

To be completely clear, I haven't actually observed this race condition to fail, I'm just noting (from reading the code) that it could.

Expected Behavior
============

I would expect the reader thread to either wait again and retry upon failure, or to wait for some other indication that the writer thread has created the resource before trying to access it.

I'd also expect the test to run through some larger multiple of ring capacity, so that inter-leaved access of the writer and reader can be guaranteed in this "concurrent" test.

Related Issues
==========

Issue #318.

**Comment by ppenna** [comment]
@BrianZill to help others spot this bug, could you add a [permanent link](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-a-permanent-link-to-a-code-snippet)  to the concerned links of code in the "How to Reproduce Section"?

**Comment by BrianZill** [comment]
> @BrianZill to help others spot this bug, could you add a [permanent link](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-a-permanent-link-to-a-code-snippet) to the concerned links of code in the "How to Reproduce Section"?

Added permalinks to each section of code mentioned in the first paragraph of the Description.

Oh, and I had marked this as both "bug" and "enhancement" as the first paragraph of the Description is about the bug, the latter section is about the proposed enhancement (checking wrap-around and more extensive interleaving).
