### ISSUE TITLE
[pdpix] Cleanup Hooks

### ISSUE THREAD

**Issue by ppenna** [microsoft/demikernel#40]
Description
========

We should add cleanup hooks to the initialization function of demikernel, so as to enable a more transparent environment cleanup experience. This function should for instance wait on all pending operations to complete as well as release any allocated resources.

**Comment by iyzhang** [comment]
This has been completed with the drop function in the NetworkLibOS and libOSes and runtimes. We hard close every queue, which cancels operations by changing the queue state. We no longer have explicit cancellation of queue operations.
