### ISSUE TITLE
[build] Automatically Set `RUST_LOG=trace` when Running in Debug Mode

### ISSUE THREAD

**Issue by ppenna** [microsoft/demikernel#403]
## Context

To facilitate debugging, we should set the `RUST_LOG` flag to `trace` level when running in debug mode.

## Proposed Solution

Change the build system to set `RUST_LOG=trace` whenever `DEBUG=yes` is set.

This should be set in build systems of both, Linux and Windows:

- [x] Linux (89a4eeaf0189b731974a3881a2aa03b7a833de32)
- [ ] Widows

**Comment by BrianZill** [comment]
As discussed in some meeting recently, could we make this `RUST_LOG=info`, or at least `debug`, instead of `trace`?  `trace` is just too verbose and should probably only be used when tracking down a specific problem.

**Comment by ppenna** [comment]
Well, we barely use the `info` and `debug` levels. Thus before moving out the `trace` level I would suggest us to get existing messages on the right levels. The idea for the setting that message level on debug mode is precisely to enable debugging output. Also, recall that we agreed that if we make the `RUST_TRACE` variable overridable in the build system, we may achieve what you are looking for - running a debug build using with a custom level.

**Comment by BrianZill** [comment]
Agreed, I'd be content with a `trace` default if `RUST_TRACE` was overridable in the build.  It is currently hard set in linux.mk.
