### ISSUE TITLE
[pal] PAL is Poorly Organized

### ISSUE THREAD

**Issue by BrianZill** [microsoft/demikernel#444]
## Context

Currently, the PAL is organized by type of thing being abstracted: constant, function, structure, etc.  And/or by platform (there currently is a linux subdirectory).

## Proposed Solution

The PAL should be organized by module: e.g. sockets, shared memory, cpu architecture, etc.  With each file organized by thing being abstracted, NOT by the platform.  The platform should be the lowest level.

**Comment by anandbonde** [comment]
PR #1422 addresses this issue.
