### ISSUE TITLE
[runtime] Move IoQueueTable into runtime

### ISSUE THREAD

**Issue by iyzhang** [microsoft/demikernel#495]
## Context

Currently, each libOS holds its own IoQueueTable and manages it. In order to support more than one libOS concurrently, we need to move the IoQueueTable to a shared, centralized place and have the Demikernel layer manage it. 

## Proposed Solution

Create a runtime trait that holds all of the shared resources, including the network runtime, the scheduler and the memory manager. The queue table would fit into that trait as a default feature.

**Comment by ppenna** [comment]
@iyzhang I believe that we can close this issue, right?

**Comment by iyzhang** [comment]
We will have to complete this before being able to support more than one libOS at a time. Not sure what milestone that belongs to.

**Comment by ppenna** [comment]
@iyzhang Sure, moving this to [Milestone 1.4](https://github.com/demikernel/demikernel/milestone/7)
