### ISSUE TITLE
[catloop] Fail When Retrying too Many Times to Establish a Connection

### ISSUE THREAD

**Issue by ppenna** [microsoft/demikernel#551]
## Context

When a Catloop LibOS peer is attempts to establish a connection and it fails, it will retry indefinitely.

https://github.com/demikernel/demikernel/blob/e13f991c60061cd9d863364d302b52e3d5ebeb27/src/rust/catloop/futures/connect.rs#L219-L221

## Proposed Solution

We should introduce impose a maximum number of retries for a connection attempt, and make the operation fail if we reach this threshold.

**Comment by vishwanath1306** [comment]
I want to pick this issue up, what is the threshold for the number of retries that should be allowed?

**Comment by ppenna** [comment]
On a solution, this should be configurable with a parameter.

**Comment by ppenna** [comment]
This is now fixed.
