### ISSUE TITLE
[catloop] Unify Table of Queue Tokens

### ISSUE THREAD

**Issue by ppenna** [microsoft/demikernel#635]
## Context

Queue tokens are registered in two tables in Catloop LibOS:
- `catmem_qts` queue tokens that are driven by the underlying Catmem LibOS (`push()` and `pop()` operations)
- `catloop_qts` queue tokens that are driven by Catloop LibOS itself (`accept()` and `connection()` operations)

If the queue token space of these operations do not collide, we should be able to use a single table for registering both types of queue tokens.

**Comment by iyzhang** [comment]
PR #891 closes this issue
