### ISSUE TITLE
[test] Fix inetstack unit test for `test_send_recv_with_delay`

### ISSUE THREAD

**Issue by iyzhang** [microsoft/demikernel#680]
## Description

Currently, our test for a simple send and receive on TCP expects does not correctly check for an ack for each send. It doesn't actually check that we got an ack for each send and, the ack may be piggybacked with the data, so we should either ensure that we received a pure ack or a piggybacked ack after each send and receive. 

## How to Reproduce

1. Add a check to recv_pure_ack for whether pop_frame_unchecked returns a packet.
2. Run test_send_recv_with_delay
3. The test fails on the second recv_pure_ack when it does not receive a packet.

## Expected Behavior

The test should check for either a pure ack or piggybacked ack on the last packet.

**Comment by ppenna** [comment]
This issue was fixed.
