### ISSUE TITLE
[runtime] Various Improvements on `DataBuffer`

### ISSUE THREAD

**Issue by anandbonde** [microsoft/demikernel#753]
We should introduce various additional fields in the `DataBuffer` abstraction:

- [ ] next and prev pointers for putting on lists w/o extra allocations
- [ ] an "extra" field that each LibOs can use for whatever it wants (we should have space for another 64 bit field in this struct before we exceed the x86 cache line size)

Related Issues
==========
- https://github.com/demikernel/runtime/pull/22
- https://github.com/demikernel/demikernel/pull/87

**Comment by iyzhang** [comment]
I'm not sure that we need any of these at this time
