### ISSUE TITLE
TCP segmentation support

### ISSUE THREAD

**Issue by ellerre** [microsoft/demikernel#847]
I am experimenting with Catnip and I would like to test the TCP performance (latency in particular) for growing payload sizes, from 64 bytes to 64 KB. To this end, I slightly modified `tcp-ping-pong.rs` to remove time-consuming operations.

For various reasons, I do not want to use jumbo frames, so I set the `MTU `to 1500 and `MSS` to 1460. Up to those sizes everything works and latency matches the expectations. However, if I try to send bigger payloads (e.g., 4096 bytes), the following assertion fails at runtime:  `mbuf.len() >= body.len()` (at `src/rust/catnip/runtime/network.rs:85`).

Specifically, the test first allocates a scatter-gather array of the requested size (in my case, 4096):

> ```
> const BUFFER_SIZE : usize = 4096;
> self.sga = Some(mksga(&mut self.libos, BUFFER_SIZE, 'a' as u8)?);
> ```

and then pushes it:

> ```
> push_and_wait(
>                     &mut self.libos,
>                     self.accepted_qd.expect("should be a valid queue descriptor"),
>                     &self.sga.expect("should be a valid sgarray"),
>                 )
> ```

I would assume that sending a payload bigger than the TCP MSS would trigger some form of automatic TCP segmentation (I see that mentioned in  #208 ), but I also read in #198 and #332 that this feature is somehow yet to be implemented. Could you clarify which is the current status of TCP segmentation in Catnip?

Should TCP segmentation be not currently possible, what would be a performance-friendly way to implement it at the application level? I think I could pre-allocate an adequate number of sga arrays, each fitting the MSS, and then modify the test to push them one after the other, and wait for all of them at receiver side. If you have better suggestions, I would be happy to hear from you!

Thank you

**Comment by ppenna** [comment]
Hello,

Our TCP stack interoperates with other TCP stacks, but it is still a work in progress towards completeness. Support for segmentation is one the missing features.

The core team is working according [to planned milestones](https://github.com/microsoft/demikernel/milestones) and eventually will implement this.
