### ISSUE TITLE
[test] TCP echo test does not test if echoes were actually completed

### ISSUE THREAD

**Issue by iyzhang** [microsoft/demikernel#987]
## Description

It is possible for the tcp echo test to not actually echo any packets. If the client successfully connects to the server kernel but then the kernel closes the connection, either the test will exit successfully or it will hang if the kernel does not close all connections. In either side the server side tcp echo application will likely hang because it did not get any connections from the OS kernel.

## How to Reproduce

1. OS kernel is up but not passing connections on to the application
2. TCP echo client gets successful connects to all clients
3. Server-side kernel closes the connections
4. TCP echo client exits if all client connections are closed, otherwise hangs.

## Documentation

This line in the TCP echo test is the problem (same between sequential and concurrent): [
](https://github.com/microsoft/demikernel/blob/2a054950f2aacff0cd0db7e9ac9277661fd64e29/examples/tcp-echo/client.rs#L122)

We are not seeing this line print out on the server and we should if the client actually connects/exits without error: [
](https://github.com/microsoft/demikernel/blob/2a054950f2aacff0cd0db7e9ac9277661fd64e29/src/rust/catnap/socket.rs#L303)

We should probably add some more application level traces, for example in each of the issue_* and handle_* functions.

## Expected Behavior

If the server-side application is not echoing data back, the test should detect that.

**Comment by ppenna** [comment]
@iyzhang could you help me elaborating on the following topics:
- Why would the OS kernel not be passing connections to the applications?
- Why would server-side kernel close connections, even without receiving any data?
- If the server is not echoing back packets, how would TCP-echo client exit?
- What is the buggy line that you wanted to highlight?
